services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/mysql:/var/lib/mysql-files
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stocks

  gateway:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf